!include <C4/C4_Container>
HIDE_STEREOTYPE()


System_Boundary(c1, "Git Info") {
    Boundary(back_b, "Info service"){
        Container(api, "API", "Go/http", "Info CRUD")
    }
}

Container_Ext(tg, "Stats", , "Manages users git activity")
Container_Ext(os, "GitHub", , "Manages repos")

Rel(tg, api, "Uses", "HTTP/REST")
Rel(api, os, "Uses", "GraphQL")
